# Generated by Django 5.0.4 on 2024-04-30 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('is_enjoyable', models.BooleanField(verbose_name='приятная')),
                ('periodicity', models.IntegerField(blank=True, choices=[(1, 'daily'), (2, 'every other day'), (3, 'every third day'), (4, 'every fourth day'), (5, 'every fifth day'), (6, 'every sixth day'), (7, 'every week')], default=1, null=True, verbose_name='периодичность')),
                ('treat', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('duration', models.DurationField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(verbose_name='публичная')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная приятная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
        ),
    ]
